### ISSUE TITLE
not working for any post request

### ISSUE THREAD

**Issue by lookis** [WildDylan/WKWebViewWithURLProtocol#2]
request body is missing after you register the scheme and make a post request on that scheme,
It's maybe a bug of webkit, discussion here:
https://bugs.webkit.org/show_bug.cgi?id=137299

and maybe here:
https://bugs.webkit.org/show_bug.cgi?id=140188

but apparently using of SPI here cannot make what you want.

**Comment by wilddylan** [comment]
There is an [issue](https://github.com/brave/browser-ios/issues/96#issuecomment-260365341) about your question.

**Comment by diegum** [comment]
Correct me if I'm wrong, but WebKit would have fixed this issue, finally. Although the solution wouldn't be yet deployed (and even when it does, there's no guarantees that all app clients will be running on a device that has the fixed WebKit version).
[This is the bug](https://bugs.webkit.org/show_bug.cgi?id=167131) that appears as fixed by mid-Jan 2017.

**Comment by diegum** [comment]
Two years before, WebKit contributor [Sam Weinig said there were no intentions to fix the bug](https://bugs.webkit.org/show_bug.cgi?id=137299#c31), because it only affected people intercepting URL protocols, which in any case was a practice that WebKit meant to keep disabled:

> After discussing this a bit, we have decided that since we do not support custom NSURLProtocols as API, there is no reason to complicate the code further by adding this functionality that no one will be allowed to use. As such, I don't think this bug is valid.

**Comment by wilddylan** [comment]
Yep, you are right. But this repo just want to handle the resources (css, js, img) request when `WKWebView` load html. WKWebView fixed the `HTTPBody` issue was awesome, but this only can let you get HTTPBody in the webView delegate what you set with `_webView loadRequest:`.  

[Discussions](http://stackoverflow.com/questions/26253133/cant-set-headers-on-my-wkwebview-post-request)

And if you have some real scene about this, welcome write it here.
